# Generated by Django 5.1.3 on 2024-12-02 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('insights', '0002_downloadlog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='insight',
            name='data_file',
        ),
    ]
